import type { ClientConfig } from "../types";

export const creationsByOracleConfig: ClientConfig = {
  key: "creations-by-oracle",
  displayName: "Creations by Oracle",
  vertical: "artist-commerce",
  theme: {
    mode: "dark",
    primaryColor: "#C084FC",
    secondaryColor: "#08060E",
    accentColor: "#F3E8FF",
    backgroundColor: "#08060E",
    textColor: "#FFFFFF",
  },
  modules: {
    cms: true,
    auth: true,
    leads: true,
    blog: true,
    services: false,
    gallery: true,
    ratings: true,
    webhooks: true,
    seo: true,
    notifications: false,
    marketingAutomation: true,
    ecommerce: true,
    artCommissions: true,
    contractorPortal: false,
    crm: true,
    calendar: false,
    pricing: false,
    chat: false,
  },
  leadPipeline: {
    vertical: "artist-commerce",
    statuses: [
      "New Inquiry",
      "Contacted",
      "Commission Proposed",
      "Commission Accepted",
      "In Progress",
      "Awaiting Payment",
      "Delivered",
      "Closed",
    ],
  },
  leadForm: [
    { key: "name", label: "Name", required: true, input: "text" },
    { key: "email", label: "Email", required: true, input: "email" },
    { key: "subject", label: "Subject", required: true, input: "text" },
    { key: "message", label: "Project Details", required: false, input: "textarea" },
  ],
  serviceSlugs: [],
  seoFocus: ["art commissions", "shop", "product storytelling"],
  frontend: {
    headerStyle: "editorial",
    footerStyle: "content-rich",
    particleLogo: {
      enabled: false,
      sourceAssetPath: "",
      morphFromUploadedLogo: false,
      sampleResolution: 0,
      primaryColor: "#C084FC",
      secondaryColor: "#F3E8FF",
      dimColor: "#6B617B",
    },
    notes: [
      "Keep this out of contractor modules.",
      "Use this as the future source for ecommerce, commissions, AI image enhancement, and product-description modules.",
    ],
  },
  cms: {
    collections: [
      { key: "journal", label: "Journal", kinds: ["post"], slugPrefix: "/blog", detailPageBasePath: "/blog", indexPagePath: "/blog", defaultPlacements: ["detail-page", "blog-index"], defaultShowInNavigation: true, defaultShowInDropdown: false },
      { key: "artwork", label: "Art Pieces", kinds: ["art-piece", "collection"], slugPrefix: "/art", detailPageBasePath: "/art", indexPagePath: "/art", defaultPlacements: ["detail-page", "blog-index", "listing-grid", "navigation-dropdown"], navigationParentKey: "art", defaultShowInNavigation: false, defaultShowInDropdown: true },
      { key: "shop", label: "Products", kinds: ["product"], slugPrefix: "/shop", detailPageBasePath: "/shop", indexPagePath: "/shop", defaultPlacements: ["detail-page", "listing-grid", "navigation-dropdown"], navigationParentKey: "shop", defaultShowInNavigation: false, defaultShowInDropdown: true },
      { key: "newsletters", label: "Newsletter", kinds: ["newsletter"], slugPrefix: "/newsletters", detailPageBasePath: "/newsletters", indexPagePath: "/newsletters", defaultPlacements: ["detail-page"], defaultShowInNavigation: false, defaultShowInDropdown: false },
    ],
    enabledKinds: ["post", "product", "art-piece", "collection", "newsletter"],
    defaultAuthoringMode: "ai-assisted",
    allowedAuthoringModes: ["manual", "ai-assisted", "ai-generated"],
    publishChannels: ["site", "blog-index", "newsletter", "subscriber-email", "rss", "seo-sitemap"],
    blogIndexKinds: ["post", "art-piece", "collection"],
    subscriberUpdateKinds: ["post", "product", "art-piece", "collection"],
    newsletter: {
      enabled: true,
      requirePreviewApproval: true,
      defaultAudienceSegment: "all-subscribers",
      allowAiSubjectLines: true,
    },
    seo: {
      aiAssistedMetadata: true,
      aiAssistedInternalLinking: true,
      aiAssistedSchemaMarkup: true,
    },
  },
  deployment: {
    backendNamespace: "creations-by-oracle",
    frontendAppName: "creations-by-oracle",
  },
};
