import type { ClientConfig } from "../types";

export const dentSocietyDfwConfig: ClientConfig = {
  key: "dent-society-dfw",
  displayName: "Dent Society DFW",
  vertical: "pdr",
  theme: {
    mode: "light",
    primaryColor: "#111111",
    secondaryColor: "#FFFFFF",
    accentColor: "#FF192C",
    backgroundColor: "#F8F7F4",
    textColor: "#111111",
  },
  modules: {
    cms: true,
    auth: true,
    leads: true,
    blog: true,
    services: true,
    gallery: false,
    ratings: true,
    webhooks: true,
    seo: true,
    notifications: false,
    marketingAutomation: true,
    ecommerce: false,
    artCommissions: false,
    contractorPortal: false,
    crm: true,
    calendar: false,
    pricing: false,
    chat: false,
  },
  leadPipeline: {
    vertical: "pdr",
    statuses: [
      "New Lead",
      "Sale Closed",
      "Claim Initiated",
      "RA Signed",
      "Loaner Assigned",
      "Vehicle In Shop",
      "Scoped",
      "Estimate Sent",
      "First Look",
      "Supplement Submitted",
      "Awaiting Approval",
      "Approved",
      "R&I",
      "PDR",
      "QC 1",
      "Reinstall",
      "QC 2",
      "Detail",
      "Ready for Delivery",
      "Delivered",
      "Closed",
    ],
  },
  leadForm: [
    { key: "name", label: "Name", required: true, input: "text" },
    { key: "phone", label: "Phone", required: true, input: "phone" },
    { key: "email", label: "Email", required: true, input: "email" },
    { key: "vehicle", label: "Vehicle", required: true, input: "text" },
    { key: "insurance", label: "Insurance", required: false, input: "text" },
    { key: "message", label: "Message", required: false, input: "textarea" },
  ],
  serviceSlugs: [
    "hail-damage-repair",
    "insurance-claim-assistance",
    "paintless-dent-repair",
    "pickup-and-delivery-service",
  ],
  seoFocus: ["DFW hail repair", "paintless dent repair", "insurance supplements"],
  frontend: {
    headerStyle: "minimal",
    footerStyle: "simple",
    particleLogo: {
      enabled: true,
      sourceAssetPath: "Dent_society_dfw/client/src/assets/Asset_7@3x-8_1770967674840.png",
      morphFromUploadedLogo: true,
      sampleResolution: 180,
      primaryColor: "#111111",
      secondaryColor: "#FF192C",
      dimColor: "#BDB8AE",
    },
    notes: [
      "Use the DFW light-mode treatment as the preferred light brand variant.",
      "Preserve the Dent Society particle-logo effect but allow theme-specific colors.",
    ],
  },
  cms: {
    collections: [
      { key: "blog", label: "Blog", kinds: ["post"], slugPrefix: "/blog", detailPageBasePath: "/blog", indexPagePath: "/blog", defaultPlacements: ["detail-page", "blog-index"], defaultShowInNavigation: true, defaultShowInDropdown: false },
      { key: "services", label: "Services", kinds: ["service"], slugPrefix: "/services", detailPageBasePath: "/services", indexPagePath: "/services", defaultPlacements: ["detail-page", "listing-grid", "navigation-dropdown"], navigationParentKey: "services", defaultShowInNavigation: false, defaultShowInDropdown: true },
      { key: "landing-pages", label: "Landing Pages", kinds: ["landing-page"], slugPrefix: "/", detailPageBasePath: "/", indexPagePath: "/", defaultPlacements: ["detail-page"], defaultShowInNavigation: false, defaultShowInDropdown: false },
    ],
    enabledKinds: ["post", "service", "landing-page", "newsletter"],
    defaultAuthoringMode: "ai-assisted",
    allowedAuthoringModes: ["manual", "ai-assisted", "ai-generated"],
    publishChannels: ["site", "blog-index", "newsletter", "subscriber-email", "rss", "seo-sitemap"],
    blogIndexKinds: ["post"],
    subscriberUpdateKinds: ["post"],
    newsletter: {
      enabled: true,
      requirePreviewApproval: true,
      defaultAudienceSegment: "all-subscribers",
      allowAiSubjectLines: true,
    },
    seo: {
      aiAssistedMetadata: true,
      aiAssistedInternalLinking: true,
      aiAssistedSchemaMarkup: true,
    },
  },
  deployment: {
    backendNamespace: "dent-society-dfw",
    frontendAppName: "dent-society-dfw",
  },
};
