import type { ClientConfig } from "../types";

export const reignServicesConfig: ClientConfig = {
  key: "reign-services",
  displayName: "Reign Services",
  vertical: "contractor",
  theme: {
    mode: "dark",
    primaryColor: "#5D3FD3",
    secondaryColor: "#0A1F44",
    accentColor: "#F5F5F7",
    backgroundColor: "#0B0B0D",
    textColor: "#F5F5F7",
  },
  modules: {
    cms: true,
    auth: true,
    leads: true,
    blog: true,
    services: true,
    gallery: true,
    ratings: true,
    webhooks: true,
    seo: true,
    notifications: false,
    marketingAutomation: true,
    ecommerce: false,
    artCommissions: false,
    contractorPortal: false,
    crm: true,
    calendar: false,
    pricing: false,
    chat: false,
  },
  leadPipeline: {
    vertical: "contractor",
    statuses: [
      "New Lead",
      "Estimate Scheduled",
      "Estimate Sent",
      "Follow Up",
      "Sale Closed",
      "Job Scheduled",
      "In Progress",
      "QC",
      "Delivered",
      "Closed",
    ],
  },
  leadForm: [
    { key: "name", label: "Name", required: true, input: "text" },
    { key: "phone", label: "Phone", required: true, input: "phone" },
    { key: "email", label: "Email", required: true, input: "email" },
    { key: "message", label: "Project Details", required: false, input: "textarea" },
  ],
  serviceSlugs: [
    "custom-turf-install",
    "foundation-repair",
    "interior-remodeling",
    "outdoor-remodeling",
    "outdoor-living",
    "turf-and-pavers",
  ],
  seoFocus: ["turf installation", "foundation repair", "outdoor living"],
  frontend: {
    headerStyle: "service-heavy",
    footerStyle: "content-rich",
    particleLogo: {
      enabled: false,
      sourceAssetPath: "",
      morphFromUploadedLogo: false,
      sampleResolution: 0,
      primaryColor: "#5D3FD3",
      secondaryColor: "#0A1F44",
      dimColor: "#2A2A30",
    },
    notes: [
      "Use this as the first contractor-core frontend target for shared-engine wiring.",
    ],
  },
  cms: {
    collections: [
      { key: "blog", label: "Blog", kinds: ["post"], slugPrefix: "/blog", detailPageBasePath: "/blog", indexPagePath: "/blog", defaultPlacements: ["detail-page", "blog-index"], defaultShowInNavigation: true, defaultShowInDropdown: false },
      { key: "services", label: "Services", kinds: ["service"], slugPrefix: "/services", detailPageBasePath: "/services", indexPagePath: "/services", defaultPlacements: ["detail-page", "listing-grid", "navigation-dropdown"], navigationParentKey: "services", defaultShowInNavigation: false, defaultShowInDropdown: true },
      { key: "landing-pages", label: "Landing Pages", kinds: ["landing-page"], slugPrefix: "/", detailPageBasePath: "/", indexPagePath: "/", defaultPlacements: ["detail-page"], defaultShowInNavigation: false, defaultShowInDropdown: false },
    ],
    enabledKinds: ["post", "service", "landing-page", "newsletter"],
    defaultAuthoringMode: "ai-assisted",
    allowedAuthoringModes: ["manual", "ai-assisted", "ai-generated"],
    publishChannels: ["site", "blog-index", "newsletter", "subscriber-email", "rss", "seo-sitemap"],
    blogIndexKinds: ["post"],
    subscriberUpdateKinds: ["post"],
    newsletter: {
      enabled: true,
      requirePreviewApproval: true,
      defaultAudienceSegment: "all-subscribers",
      allowAiSubjectLines: true,
    },
    seo: {
      aiAssistedMetadata: true,
      aiAssistedInternalLinking: true,
      aiAssistedSchemaMarkup: true,
    },
  },
  deployment: {
    backendNamespace: "reign-services",
    frontendAppName: "reign-services",
  },
};
