import type { ClientConfig } from "../types";

export const tachyonbuiltConfig: ClientConfig = {
  key: "tachyonbuilt",
  displayName: "TachyonBuilt Contracting",
  vertical: "contractor",
  theme: {
    mode: "dark",
    primaryColor: "#E87722",
    secondaryColor: "#1A1A1A",
    accentColor: "#F3EFE8",
    backgroundColor: "#111111",
    textColor: "#F3EFE8",
  },
  modules: {
    cms: true,
    auth: true,
    leads: true,
    blog: true,
    services: true,
    gallery: true,
    ratings: true,
    webhooks: true,
    seo: true,
    notifications: true,
    marketingAutomation: true,
    ecommerce: false,
    artCommissions: false,
    contractorPortal: true,
    crm: true,
    calendar: true,
    pricing: true,
    chat: true,
  },
  leadPipeline: {
    vertical: "contractor",
    statuses: [
      "New Lead",
      "Estimate Scheduled",
      "Estimate Sent",
      "Follow Up",
      "Sale Closed",
      "Job Scheduled",
      "In Progress",
      "QC",
      "Delivered",
      "Closed",
    ],
  },
  leadForm: [
    { key: "name", label: "Name", required: true, input: "text" },
    { key: "phone", label: "Phone", required: true, input: "phone" },
    { key: "email", label: "Email", required: true, input: "email" },
    { key: "message", label: "Project Scope", required: false, input: "textarea" },
  ],
  serviceSlugs: [
    "wood-staining",
    "fence-restoration",
    "power-washing",
    "window-cleaning",
    "soil-enhancement",
    "turf-installation",
    "outdoor-living",
  ],
  seoFocus: ["outdoor services", "service city pages", "contractor portal"],
  frontend: {
    headerStyle: "service-heavy",
    footerStyle: "content-rich",
    particleLogo: {
      enabled: false,
      sourceAssetPath: "",
      morphFromUploadedLogo: false,
      sampleResolution: 0,
      primaryColor: "#E87722",
      secondaryColor: "#F3EFE8",
      dimColor: "#5B5B5B",
    },
    notes: [
      "Treat TachyonBuilt as the contractor feature superset for portal, chat, calendar, and pricing.",
    ],
  },
  cms: {
    collections: [
      { key: "blog", label: "Blog", kinds: ["post"], slugPrefix: "/blog", detailPageBasePath: "/blog", indexPagePath: "/blog", defaultPlacements: ["detail-page", "blog-index"], defaultShowInNavigation: true, defaultShowInDropdown: false },
      { key: "services", label: "Services", kinds: ["service"], slugPrefix: "/services", detailPageBasePath: "/services", indexPagePath: "/services", defaultPlacements: ["detail-page", "listing-grid", "navigation-dropdown"], navigationParentKey: "services", defaultShowInNavigation: false, defaultShowInDropdown: true },
      { key: "landing-pages", label: "Landing Pages", kinds: ["landing-page"], slugPrefix: "/", detailPageBasePath: "/", indexPagePath: "/", defaultPlacements: ["detail-page"], defaultShowInNavigation: false, defaultShowInDropdown: false },
    ],
    enabledKinds: ["post", "service", "landing-page", "newsletter"],
    defaultAuthoringMode: "ai-assisted",
    allowedAuthoringModes: ["manual", "ai-assisted", "ai-generated"],
    publishChannels: ["site", "blog-index", "newsletter", "subscriber-email", "rss", "seo-sitemap"],
    blogIndexKinds: ["post"],
    subscriberUpdateKinds: ["post"],
    newsletter: {
      enabled: true,
      requirePreviewApproval: true,
      defaultAudienceSegment: "all-subscribers",
      allowAiSubjectLines: true,
    },
    seo: {
      aiAssistedMetadata: true,
      aiAssistedInternalLinking: true,
      aiAssistedSchemaMarkup: true,
    },
  },
  deployment: {
    backendNamespace: "tachyonbuilt",
    frontendAppName: "tachyonbuilt",
  },
};
